// <auto-generated />
namespace WebVDRS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class faculty_major : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(faculty_major));
        
        string IMigrationMetadata.Id
        {
            get { return "202001240037529_faculty_major"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
